### ISSUE TITLE
multiple values for argument 'nb_bins' in tutorial_pynapple_quick_start.py

### ISSUE THREAD

**Issue by WeissShahaf** [PeyracheLab/pynapple#108]
i'm trying to follow your tutorial, but getting an error on nb_bins:

runfile('F:/Dropbox/Postdoc/code/pynapple/docs/tutorials/tutorial_pynapple_quick_start.py', wdir='F:/Dropbox/Postdoc/code/pynapple/docs/tutorials')
Reloaded modules: pynapple.core.time_units, pynapple.core.interval_set, pynapple.core.time_series, pynapple.core.ts_group, pynapple.core, pynapple.io.loader_gui, pynapple.io.loader, pynapple.io.ophys_gui, pynapple.io.cnmfe, pynapple.io.ephys_gui, pynapple.io.neurosuite, pynapple.io.phy, pynapple.io.misc, pynapple.io, pynapple.process.correlograms, pynapple.process.decoding, pynapple.process.perievent, pynapple.process.tuning_curves, pynapple.process, pynapple
                  rx        ry        rz         x         y         z
Time (s)                                                              
670.64070   0.343163  5.207148  5.933598 -0.042857  0.425023 -0.195725
670.64900   0.346745  5.181029  5.917368 -0.043863  0.424850 -0.195110
670.65735   0.344035  5.155508  5.905679 -0.044853  0.424697 -0.194674
670.66565   0.322240  5.136537  5.892457 -0.045787  0.424574 -0.194342
670.67400   0.315836  5.120850  5.891577 -0.046756  0.424563 -0.194059
             ...       ...       ...       ...       ...       ...
1199.96160  6.009812  3.665954  0.230562  0.011241  0.037891 -0.001479
1199.96995  6.014660  3.634619  0.260742  0.010974  0.038677 -0.002370
1199.97825  6.031694  3.617849  0.276835  0.010786  0.039410 -0.003156
1199.98660  6.040435  3.609446  0.287006  0.010661  0.040064 -0.003821
1199.99495  6.050059  3.609375  0.293275  0.010624  0.040568 -0.004435

[63527 rows x 6 columns]
  Index    Freq. (Hz)    group  location
-------  ------------  -------  ----------
      0          4.85        0  adn
      1          8.06        0  adn
      2          7.11        0  adn
      3          7.66        0  adn
      4          7.97        0  adn
      5         11.29        0  adn
      6         22.08        0  adn
      7          1.82        1  ca1
      8          2.84        1  ca1
      9          0.7         1  ca1
     10          4.78        1  ca1
     11          4.93        1  ca1
     12          1.71        1  ca1
     13          0.97        1  ca1
     14          0.26        1  ca1
        start         end
0  682.660850  745.565725
1  752.240350  752.440325
2  752.582000  752.673650
3  757.498375  758.998300
4  789.863275  790.271575
5  875.225250  876.066875
6  878.158425  878.641725
  Index    Freq. (Hz)    group  location
-------  ------------  -------  ----------
      0          7.3         0  adn
      1          5.73        0  adn
      2          8.12        0  adn
      3          6.68        0  adn
      4         10.77        0  adn
      5         11           0  adn
      6         16.52        0  adn
  Index    Freq. (Hz)    group  location
-------  ------------  -------  ----------
      7          2.2         1  ca1
      8          2.02        1  ca1
      9          1.07        1  ca1
     10          3.92        1  ca1
     11          3.31        1  ca1
     12          1.09        1  ca1
     13          1.28        1  ca1
     14          1.32        1  ca1
Traceback (most recent call last):

  File "C:\ProgramData\Miniconda3\envs\pynapple\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "f:\dropbox\postdoc\code\pynapple\docs\tutorials\tutorial_pynapple_quick_start.py", line 221, in <module>
    tuning_curves_adn = nap.compute_1d_tuning_curves(spikes_adn,position['ry'],position['ry'].time_support,nb_bins=121,minmax=(0, 2*np.pi))

TypeError: compute_1d_tuning_curves() got multiple values for argument 'nb_bins'

**Comment by gviejo** [comment]
Hello Weiss, 

Just to know, did you pip install from the pypi repository or did you install the github repository with the latest changes?

**Comment by WeissShahaf** [comment]
I cloned the GitHub repo

Shahaf Weiss, PhD

Max Planck Institute for Brain Research

NSK - Laurent department
Max-von-Laue-Str. 4
60438 Frankfurt am Main, Germany
www.brain.mpg.de

***@***.***

***@***.***

Tel:+49 17657814689

**Comment by gviejo** [comment]
I found the issue. The correct way is 
tuning_curves = nap.compute_1d_tuning_curves(spikes, position['ry'], 121, ep=position['ry'].time_support, minmax=(0, 2*np.pi))

Not sure how it went unnoticed.
I am updating all the notebooks and pushing it again. Thanks Shahaf for opening the issue.

**Comment by gviejo** [comment]
Hey actually I noticed that you were looking at old versions of the notebooks. The right versions are here :

https://github.com/PeyracheLab/pynapple/tree/main/docs/notebooks

Let me know if you have other issue.

Guillaume

**Comment by WeissShahaf** [comment]
i was using the .py file, not the notebook
