### ISSUE TITLE
Error loading Phy data

### ISSUE THREAD

**Issue by javierzsm** [PeyracheLab/pynapple#96]
Hi, 
I can't figure what's the issue here. I am trying to load some Phy data

My code:
```
import numpy as np
import pandas as pd
import pynapple as nap

data_directory = r'C:\Users\javier.zorrilla\Documents\NPX_OpenEphys_SampleData\kilosort3'

data = nap.load_session(data_directory, 'phy')

spikes = data.spikes
position = data.position
epochs = data.epochs

print(spikes)
```

and I get this error:

Traceback (most recent call last):

  File "C:\Users\javier.zorrilla\Anaconda3\envs\pynapple\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "\\l2export\iss02.bacci\trisomic-alpha5\javier\analysis\pynapple\crash_test_pynapple.py", line 10, in <module>
    data = nap.load_session(data_directory,

  File "C:\Users\javier.zorrilla\Anaconda3\envs\pynapple\lib\site-packages\pynapple\io\misc.py", line 53, in load_session
    return Phy(path)

  File "C:\Users\javier.zorrilla\Anaconda3\envs\pynapple\lib\site-packages\pynapple\io\phy.py", line 55, in __init__
    self.load_phy_spikes(path, self.time_support)

  File "C:\Users\javier.zorrilla\Anaconda3\envs\pynapple\lib\site-packages\pynapple\io\phy.py", line 134, in load_phy_spikes
    cluster_id_good = self.cluster_group[self.cluster_group.group=='good'].index.values

  File "C:\Users\javier.zorrilla\Anaconda3\envs\pynapple\lib\site-packages\pandas\core\generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'group'

**Comment by vigji** [comment]
Getting same error here, after running KiloSort 3 on the data and creating the phy data folder (no manual curation with phy done on the data yet, though).
If I read the data frame directly with `pandas`, it seems that the column is not `group` but `KSLabel`, is this correct?

**Comment by javierzsm** [comment]
@vigji thanks to your comment I found the issue. 

For some reason I was missing the cluster_info.tsv file.

I curated again the ks3 data and rewrote all the Phy output.

cluster_info.tsv is now properly loaded into a dataFrame and has a column named 'group'.

Thanks and sorry for the noise. I hope it helps somebody else.

**Comment by vigji** [comment]
Still, maybe it's worth adding the option of dealing with uncurated data, happy to do a PR with my fix

**Comment by gviejo** [comment]
Hey guys, happy it was solved easily. Related to the flexible loading of phy data, yes I agree that it should be done. Please feel free to submit a PR.
